### ISSUE TITLE
生成图片报错

### ISSUE THREAD

**Issue by 97612336** [pyecharts/pyecharts#1030]
**问题**
不能生成图片

**运行环境（系统环境及 pyecharts 版本）**
运行环境：python3.6.5
系统环境：deepin linux
pyecharts：0.5.11

**代码及截图**
代码：
`from pyecharts import Bar

bar = Bar("主标题", "副标题", is_animation=False)
bar.add('衣服', [1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
bar.render('a.png')`

报错：
`Traceback (most recent call last):
  File "/home/wangkun/PycharmProjects/mytest/painter_test/painter_and_create_wordfile.py", line 8, in <module>
    bar.render('a.png')
  File "/home/wangkun/.python_env/test/lib/python3.6/site-packages/pyecharts/base.py", line 140, in render
    env = engine.create_default_environment(_file_type)
  File "/home/wangkun/.python_env/test/lib/python3.6/site-packages/pyecharts/engine.py", line 280, in create_default_environment
    [config.echarts_template_dir, default_template_dir]
  File "/home/wangkun/.python_env/test/lib/python3.6/site-packages/pyecharts/engine.py", line 260, in get_a_environment
    key=file_type
  File "/home/wangkun/.python_env/test/lib/python3.6/site-packages/lml/plugin.py", line 289, in load_me_now
    self.raise_exception(key)
  File "/home/wangkun/.python_env/test/lib/python3.6/site-packages/lml/plugin.py", line 240, in raise_exception
    "No %s is found for %s" % (self.plugin_name, key))
Exception: No pyecharts_environment is found for png`

**Comment by sunhailin-Leo** [comment]
@97612336 pyecharts-snapshot 装了么？

**Comment by 97612336** [comment]
> @97612336 pyecharts-snapshot 装了么？

pyecharts-snapshot 版本是： 0.2.0

**Comment by chenjiandongx** [comment]
#1033 用 1.0.0 啦，0.5.X 已经不再维护啦

**Comment by zonenAnna** [comment]
请问楼主解决了吗？我这正愁这个问题呢呜呜呜
