### ISSUE TITLE
we just run example/graph_example.py

### ISSUE THREAD

**Issue by loveJasmine** [pyecharts/pyecharts#1503]
**问题**
G:\ub16_prj\bumblebee>pip install pyecharts
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyecharts
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fc/15/c30e542fcf1245eaa0198327879e7869c2c49c600611b2b2d70fbbbcd252/pyecharts-1.6.2-py3-none-any.whl (168 kB)
     |████████████████████████████████| 168 kB 1.1 MB/s
Requirement already satisfied: jinja2 in c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages (from pyecharts) (2.10.3)
Requirement already satisfied: simplejson in c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages (from pyecharts) (3.13.2)
Requirement already satisfied: prettytable in c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages (from pyecharts) (0.7.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages (from jinja2->pyecharts) (1.1.0)
Installing collected packages: pyecharts
Successfully installed pyecharts-1.6.2

G:\ub16_prj\bumblebee>python pyecharts.py
Traceback (most recent call last):
  File "pyecharts.py", line 8, in <module>
    from pyecharts.commons.utils import JsCode
  File "G:\ub16_prj\bumblebee\pyecharts.py", line 8, in <module>
    from pyecharts.commons.utils import JsCode
ModuleNotFoundError: No module named 'pyecharts.commons'; 'pyecharts' is not a package

G:\ub16_prj\bumblebee>

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chfw** [comment]
Never ever name your script file as pyecharts.py
