### ISSUE TITLE
新手想问一下问题,关于运行例子代码的TypeError

### ISSUE THREAD

**Issue by Tong-Guin** [pyecharts/pyecharts#1607]
**问题**
当我复制demo的代码时,无论哪个图表,都会出现错误,但是在Jupyter Notebook里可以直接运行,实在不知道为什么会多出参数来
TypeError: get() takes 2 positional arguments but 3 were given

具体错误如下:
Traceback (most recent call last):

  File "E:\未命名0.py", line 18, in <module>
    Bar()

  File "F:\Anaconda3\anaconda3\lib\site-packages\pyecharts\charts\chart.py", line 163, in __init__
    super().__init__(init_opts=init_opts)

  File "F:\Anaconda3\anaconda3\lib\site-packages\pyecharts\charts\chart.py", line 14, in __init__
    super().__init__(init_opts=init_opts)

  File "F:\Anaconda3\anaconda3\lib\site-packages\pyecharts\charts\base.py", line 28, in __init__
    self.width = _opts.get("width", "900px")

TypeError: get() takes 2 positional arguments but 3 were given

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.7.1
anaconda 3
python 3.7.6

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Tong-Guin  Show me your code and snapshot.
