### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

### ISSUE THREAD

**Issue by DylanDenali** [pyecharts/pyecharts#1790]
Traceback (most recent call last):
  File "D:/SpiderProgram/info_analysis/hotmap_China.py", line 21, in <module>
    make_snapshot(driver, bar_chart().render(), "bar.png")
  File "D:\Anaconda\lib\site-packages\pyecharts\render\snapshot.py", line 37, in make_snapshot
    **kwargs,
  File "D:\Anaconda\lib\site-packages\snapshot_selenium\snapshot.py", line 35, in make_snapshot
    driver = get_chrome_driver()
  File "D:\Anaconda\lib\site-packages\snapshot_selenium\snapshot.py", line 58, in get_chrome_driver
    return webdriver.Chrome(options=options)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

**Comment by sunhailin-Leo** [comment]
@DylanDenali 
* Maybe your selenium, chrome driver version, or chrome browser version is incompatible.
