### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'keep_trailing_newline'

### ISSUE THREAD

**Issue by alanzhai219** [pyecharts/pyecharts#1967]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

1.9.1

**代码及截图**

```bash
python                                                           
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyecharts.charts import Bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/__init__.py", line 1, in <module>
    from pyecharts import charts, commons, components, datasets, options, render, scaffold
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/charts/__init__.py", line 2, in <module>
    from ..charts.basic_charts.bar import Bar
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/charts/basic_charts/bar.py", line 1, in <module>
    from ... import options as opts
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/options/__init__.py", line 3, in <module>
    from .charts_options import (
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/options/charts_options.py", line 3, in <module>
    from ..globals import BMapType
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/globals.py", line 146, in <module>
    class _CurrentConfig:
  File "/home/zxc/bin/conda/lib/python3.6/site-packages/pyecharts/globals.py", line 156, in _CurrentConfig
    os.path.abspath(os.path.dirname(__file__)), "render", "templates"
TypeError: __init__() got an unexpected keyword argument 'keep_trailing_newline'
```

**Comment by Crojav** [comment]
Got a simular sitation here:
Python3 on LinuxMint
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from pyecharts import Bar
ImportError: cannot import name 'Bar' from 'pyecharts' (/usr/local/lib/python3.8/dist-packages/pyecharts-1.9.1-py3.8.egg/pyecharts/__init__.py)

**Comment by sunhailin-Leo** [comment]
@alanzhai219 
* 你用的 jinja 的版本低于 2.7 吧？
```html
 `keep_trailing_newline`
            Preserve the trailing newline when rendering templates.
            The default is ``False``, which causes a single newline,
            if present, to be stripped from the end of the template.
            .. versionadded:: 2.7
```

**Comment by sunhailin-Leo** [comment]
> ```shell
> from pyecharts.charts import Bar
> ```

* In `pyecharts` 1.x ==> `from pyecharts.charts import Bar` instead of `from pyecharts import Bar`(0.5.x way)

**Comment by Crojav** [comment]
from pyecharts.charts import Bar <<< Works!

Note that I did a install from github:

$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts
$ pip install -r requirements.txt
$ python setup.py install

and got that ImportError: cannot import name 'Bar' from 'pyechart
