### ISSUE TITLE
macos 不能正常运行 

### ISSUE THREAD

**Issue by spacexnasa** [pyecharts/pyecharts#2009]
看了 issues，没有类似情况
intel macos 

pip install pyecharts
Collecting pyecharts
  Using cached pyecharts-1.9.1-py3-none-any.whl (135 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/site-packages (from pyecharts) (2.11.3)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/site-packages (from pyecharts) (3.2.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.10/site-packages (from pyecharts) (3.17.6)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.10/site-packages (from jinja2->pyecharts) (2.1.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/site-packages (from prettytable->pyecharts) (0.2.5)
Installing collected packages: pyecharts

安装都正常

导入出问题
 python
Python 3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyecharts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pyecharts/__init__.py", line 1, in <module>
    from pyecharts import charts, commons, components, datasets, options, render, scaffold
  File "/usr/local/lib/python3.10/site-packages/pyecharts/charts/__init__.py", line 2, in <module>
    from ..charts.basic_charts.bar import Bar
  File "/usr/local/lib/python3.10/site-packages/pyecharts/charts/basic_charts/bar.py", line 1, in <module>
    from ... import options as opts
  File "/usr/local/lib/python3.10/site-packages/pyecharts/options/__init__.py", line 3, in <module>
    from .charts_options import (
  File "/usr/local/lib/python3.10/site-packages/pyecharts/options/charts_options.py", line 3, in <module>
    from ..globals import BMapType
  File "/usr/local/lib/python3.10/site-packages/pyecharts/globals.py", line 3, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)

**Comment by spacexnasa** [comment]
pip install Jinja2==3.1.1 ok 了
