### ISSUE TITLE
 Table - Table_base   使用snapshot_selenium 、snapshot-pyppeteer  均无法生成图片

### ISSUE THREAD

**Issue by Nicolasking007** [pyecharts/pyecharts#2046]
**问题**
`from pyecharts.components import Table`

使用`snapshot_selenium` 、`snapshot-pyppeteer`   均无法生成图片

**运行环境（系统环境及 pyecharts 版本）**
window 版本 `11`
pyecharts 版本 `1.9.0 `

**代码及截图**
`Traceback (most recent call last):
  File "E:\CodeShare\demo.py", line 38, in <module>
    make_snapshot(snapshot, table.render(), f"{now_time}油价.png")
  File "E:\CodeShare\venv\lib\site-packages\pyecharts\render\snapshot.py", line 32, in make_snapshot
    content = engine.make_snapshot(
  File "E:\CodeShare\venv\lib\site-packages\snapshot_selenium\snapshot.py", line 52, in make_snapshot
    return driver.execute_script(snapshot_js)
  File "E:\CodeShare\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 493, in execute_script
    return self.execute(command, {
  File "E:\CodeShare\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "E:\CodeShare\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: echarts is not defined
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x00DC6463+2188387]
	Ordinal0 [0x00D5E461+1762401]
	Ordinal0 [0x00C73D78+802168]
	Ordinal0 [0x00C76754+812884]
	Ordinal0 [0x00C76612+812562]
	Ordinal0 [0x00C76F8A+814986]
	Ordinal0 [0x00CCD669+1169001]
	Ordinal0 [0x00CBC7DC+1099740]
	Ordinal0 [0x00CCCC22+1166370]
	Ordinal0 [0x00CBC5F6+1099254]
	Ordinal0 [0x00C96BE0+945120]
	Ordinal0 [0x00C97AD6+948950]
	GetHandleVerifier [0x010671F2+2712546]
	GetHandleVerifier [0x0105886D+2652765]
	GetHandleVerifier [0x00E5002A+520730]
	GetHandleVerifier [0x00E4EE06+516086]
	Ordinal0 [0x00D6468B+1787531]
	Ordinal0 [0x00D68E88+1805960]
	Ordinal0 [0x00D68F75+1806197]
	Ordinal0 [0x00D71DF1+1842673]
	BaseThreadInitThunk [0x76756739+25]
	RtlGetFullPathName_UEx [0x77B78FEF+1215]
	RtlGetFullPathName_UEx [0x77B78FBD+1165]`

**Comment by Nicolasking007** [comment]
示例代码
`from pyecharts.components import Table
from pyecharts.options import ComponentTitleOpts
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot
# from snapshot_pyppeteer import snapshot
import time

now = time.localtime()
now_time = time.strftime("%Y%m%d", now)

table = Table()

headers = ["City name", "Area", "Population", "Annual Rainfall"]
rows = [
    ["Brisbane", 5905, 1857594, 1146.4],
    ["Adelaide", 1295, 1158259, 600.5],
    ["Darwin", 112, 120900, 1714.7],
    ["Hobart", 1357, 205556, 619.5],
    ["Sydney", 2058, 4336374, 1214.8],
    ["Melbourne", 1566, 3806092, 646.9],
    ["Perth", 5386, 1554769, 869.4],
]
table.add(headers, rows)
table.set_global_opts(
    title_opts=ComponentTitleOpts(title="Table-基本示例", subtitle="我是副标题支持换行哦")
)
# table.render("table_base.html")
make_snapshot(snapshot, table.render(), f"{now_time}油价.png")
print('图片生成成功')
`
