### ISSUE TITLE
How to customize template used to render Echarts?

### ISSUE THREAD

**Issue by samzhangjy** [pyecharts/pyecharts#2067]
Hi. Thanks for creating this awesome project! I'm currently having a difficulty with customizing Jinja templates. I'm aware of #370 and #228, but all links / code have been expired.

I've tried to use the `Graph` chart and display some relations between nodes. After trying to set `template_name` on the `render` method, I encountered the following error:

```python
 graph.render(template_name=os.path.abspath("./templates/relations.html"))
```

```
Traceback (most recent call last):
  File "/Volumes/Data/Develop/relationship/core/__init__.py", line 62, in <module>
    analyzer.generate_graph()
  File "/Volumes/Data/Develop/relationship/core/__init__.py", line 53, in generate_graph
    graph.render(template_name=os.path.abspath("./templates/relations.html"))
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/pyecharts/charts/base.py", line 65, in render
    return engine.render(self, path, template_name, env, **kwargs)
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/pyecharts/render/engine.py", line 74, in render
    RenderEngine(env).render_chart_to_file(
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/pyecharts/render/engine.py", line 54, in render_chart_to_file
    tpl = self.env.get_template(template_name)
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Volumes/Data/Develop/relationship/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /Volumes/Data/Develop/relationship/templates/relations.html
```

After digging the source code, I discovered that the Jinja environment is created inside PyEcharts and I don't know how to customize it. I've found some documentation [here](https://pyecharts.org/#/en-us/api?id=template-engine) about the Template Engine but it seemed to be outdated.

So I wanted to know if we can still change the Jinja template used to render charts in the latest releases of PyEcharts?

Thanks in advance!

**Comment by sunhailin-Leo** [comment]
@samzhangjy 
* Our source code has some templates in `render/template` folder, so you can update your template to replace it now.
* In the feature, I will add an argument to load custom templates by the developer.
