### ISSUE TITLE
没有xAxis的图表第一个加入grid时报错，且无法调整位置、大小

### ISSUE THREAD

**Issue by gojuukaze** [pyecharts/pyecharts#2101]
一共两个问题

1. 把没有`xAxis`, `yxAxis`的图表(geo, map ,pie等) 放到grid的第一个时会报错
2. 无法调整位置，只能显示在最中间，也无法修改宽高

代码如下

```python
from pyecharts import options as opts
from pyecharts.charts import Bar, Geo, Grid,Line
from pyecharts.faker import Faker

bar = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .set_global_opts(legend_opts=opts.LegendOpts(is_show=False),
                     tooltip_opts=opts.TooltipOpts(is_show=False)
                     )
)
geo = (
    Geo()
    .add_schema(maptype="china")
    .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
         tooltip_opts=opts.TooltipOpts(is_show=True)
    )
)

grid = (
    Grid()
    .add(geo, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
    .add(bar2, grid_opts=opts.GridOpts(pos_left="60%"))
    .render()
)
```

报错如下：

```
Traceback (most recent call last):
  File "d:\code\chart\test.py", line 48, in <module>
    .add(bar2, grid_opts=opts.GridOpts(pos_left="60%"))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\john\AppData\Roaming\Python\Python311\site-packages\pyecharts\charts\composite_charts\grid.py", line 76, in add
    self.options.get("xAxis").extend(chart.options.get("xAxis"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'extend'
```

**Comment by sunhailin-Leo** [comment]
@gojuukaze 
* `Grid` 的说明文档和代码设计的时候本来就是给直角坐标系的图使用的。
* 非直角坐标系的图能够 `add` 进去是因为通过 `_axis_index` 参数控制的，但是因为非直角系的图并没有 `xAxis` 和 `yAxis`，因此不能作为第一个图进行添加。
* 关于使用顺序的问题，作图的时候稍加注意即可
