### ISSUE TITLE
使用Gird绘制Candlestick组合图时，无法添加多张子图，只要grid_index>2就会显示不正常

### ISSUE THREAD

**Issue by EnjoyLeole** [pyecharts/pyecharts#2281]
使用Gird绘制Candlestick组合图时，只要添加的子图数量多，grid_index>2之后就会显示不正常，直接无任何显示
将子图grid_index=2， 可以重叠显示出内容

windows和mac系统均出现了这个问题

**Comment by EnjoyLeole** [comment]
经测试，应该是使用双坐标轴导致的问题
浏览器报错如下：

echarts.min.js:45  Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at Object.reset (echarts.min.js:45:352188)
    at t.ty [as _reset] (echarts.min.js:45:174667)
    at t._doReset (echarts.min.js:45:135579)
    at t.perform (echarts.min.js:45:134592)
    at echarts.min.js:45:172579
    at echarts.min.js:35:8394
    at Map.forEach (<anonymous>)
    at t.each (echarts.min.js:35:8369)
    at echarts.min.js:45:172420
    at Array.forEach (<anonymous>)

**Comment by sunhailin-Leo** [comment]
@EnjoyLeole 
* https://gallery.pyecharts.org/#/Grid/grid_overlap_multi_xy_axis
