### ISSUE TITLE
js加载又又又出问题了，无法显示

### ISSUE THREAD

**Issue by LY1806620741** [pyecharts/pyecharts#2386]
**问题**
cell1:
```python
from pyecharts.charts import Pie
from pyecharts import options as opts
from pyecharts.globals import CurrentConfig

# 设置国内 CDN 配置
CurrentConfig.ONLINE_HOST = "https://cdn.jsdelivr.net/npm/echarts@latest/dist/"

# 准备数据
labels = list(annotationCounter.keys())
sizes = list(annotationCounter.values())

# 创建饼图
pie = (
    Pie()
    .add("", list(zip(labels, sizes)))
    .set_global_opts(title_opts=opts.TitleOpts(title="Category Percentages"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c} ({d}%)"))
)
pie.load_javascript()
""
```
cell2:
```python
pie.render_notebook()
```

错误：chrome控制台错误
```javascript
VM888:2 Uncaught ReferenceError: require is not defined
    at <anonymous>:2:5
    at w.attachWidget (911.bundle.js:1:18414)
    at w.insertWidget (911.bundle.js:1:17908)
    at x._insertOutput (7226.bundle.js:1:10480)
    at x.onModelChanged (7226.bundle.js:1:6951)
    at a (409.bundle.js:1:2625)
    at e.emit (409.bundle.js:1:2354)
    at o.emit (409.bundle.js:1:334)
    at d._onListChanged (7226.bundle.js:1:2895)
    at a (409.bundle.js:1:2625)
(anonymous) @ VM888:2
attachWidget @ 911.bundle.js:1
insertWidget @ 911.bundle.js:1
_insertOutput @ 7226.bundle.js:1
onModelChanged @ 7226.bundle.js:1
a @ 409.bundle.js:1
e.emit @ 409.bundle.js:1
emit @ 409.bundle.js:1
_onListChanged @ 7226.bundle.js:1
a @ 409.bundle.js:1
e.emit @ 409.bundle.js:1
emit @ 409.bundle.js:1
push @ 170.bundle.js:1
_add @ 7226.bundle.js:1
add @ 7226.bundle.js:1
_onIOPub @ 7226.bundle.js:1
_handleIOPub @ 3676.bundle.js:1
await in _handleIOPub
handleMsg @ 3676.bundle.js:1
_handleMessage @ 3676.bundle.js:1
(anonymous) @ 3676.bundle.js:1
Promise.then
_onWSMessage @ 3676.bundle.js:1
VM889:2 Uncaught ReferenceError: require is not defined
    at <anonymous>:2:9
    at w.attachWidget (911.bundle.js:1:18414)
    at w.insertWidget (911.bundle.js:1:17908)
    at x._insertOutput (7226.bundle.js:1:10480)
    at x.onModelChanged (7226.bundle.js:1:6951)
    at a (409.bundle.js:1:2625)
    at e.emit (409.bundle.js:1:2354)
    at o.emit (409.bundle.js:1:334)
    at d._onListChanged (7226.bundle.js:1:2895)
    at a (409.bundle.js:1:2625)
```

**运行环境（系统环境及 pyecharts 版本）**

```shell
> pip freeze |Findstr pyechart
pyecharts==2.0.6

>python -V
Python 3.13.0

> pip freeze |Findstr jupyter   
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13

> systeminfo |Select-String "^OS"

OS 名称:          Microsoft Windows 11 企业版
OS 版本:          10.0.22631 暂缺 Build 22631
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
```

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@LY1806620741 
* 不加 `CurrentConfig.ONLINE_HOST` 呢？

**Comment by LY1806620741** [comment]
@sunhailin-Leo

一样的，就是无法加载才换host的，能否本地内置啊
