### ISSUE TITLE
雷达图html渲染生成正常但是make_snapshot输出图片空白

### ISSUE THREAD

**Issue by exqmjmz** [pyecharts/pyecharts#2395]
**问题**
通过本地加载echarts.min.js
饼图、柱状图、折线图、地图都可以正常渲染出图片
但是 雷达图 可以正常输出html，通过make_snapshot+snapshot_phantomjs输出的图片是空白的

**运行环境（系统环境及 pyecharts 版本）**
系统:MAC OS 14
Python版本:3.9
Pyecharts版本:2.0.7

**代码及截图**
![image](https://github.com/user-attachments/assets/92e050e4-8b2e-4370-bd66-ed365b0ca509)

![image](https://github.com/user-attachments/assets/d6d0d8bd-f3d9-4511-afd6-15c00c3412ff)

![image](https://github.com/user-attachments/assets/e7af2445-e516-4724-8f39-e1c0060cc593)

入参:
```json
{
    "category": ["Sales", "Administration", "Information Technology", "Customer Support", "Development", "Marketing"],
    "type": "radar",
    "data": [
        {
          "value": [4200, 3000, 20000, 35000, 50000, 18000],
          "name": "Allocated Budget"
        },
        {
          "value": [5000, 14000, 28000, 26000, 42000, 21000],
          "name": "Actual Spending"
        }
    ]
}
```

代码:
```python
class RadarChart:
    def __init__(self,category,type, data:List):
        # 修改echarts.min.js为本地调用
        CurrentConfig.ONLINE_HOST = config.echartjsHost
        self.radar = Radar(init_opts=opts.InitOpts(
            bg_color='white', width="1000px", height="1000px"
        ))
        self.htmlPath =os.path.join(config.imagePath+type+str(int(time.time_ns()/1000))+".html")
        self.imagePath = os.path.join(config.imagePath+type+str(int(time.time_ns()/1000))+".jpeg")
        self.chartType = type
        self.category = category
        self.data = data
        self.maxData = []
        # 找出入参的最大值
        for item in self.data:
            value = item["value"]
            for i in range(len(value)):
                if len(value)> len(self.maxData):
                    self.maxData.append(value[i])
                elif value[i] > self.maxData[i]:
                    self.maxData[i]=value[i]

    def render(self):
        if self.chartType=="radar":
            self._renderRadar()
    
    def _renderRadar(self):
        radar = self.radar
        radarSchema = []
        # 给每个参数最大值再加10%，避免label贴到图形边缘上
        for i in range(len(self.category)):
            item = self.category[i]
            max = self.maxData[i]+(self.maxData[i]*0.1)
            radarSchema.append({"name": item, "max": max})
        radar.add_schema(schema=radarSchema)
        radarItems = []
        for item in self.data:
            radarItem = opts.RadarItem(name=item["name"], value=item["value"])
            radarItems.append(radarItem)
        radar.add(series_name="", data=radarItems)
        radar.render(self.htmlPath)
        make_snapshot(snapshot, self.htmlPath, self.imagePath)
```

**Comment by sunhailin-Leo** [comment]
@exqmjmz 
* 看浏览器控制台有没有报错？

**Comment by exqmjmz** [comment]
> @exqmjmz
> 
> * 看浏览器控制台有没有报错？

正常，无报错

![image](https://github.com/user-attachments/assets/e9d1feb1-eaf1-4a4e-9c14-f1f4de9c3675)

**Comment by sunhailin-Leo** [comment]
@exqmjmz 
* 你 snapshot 用的哪个组件？

**Comment by exqmjmz** [comment]
> @exqmjmz
> 
> * 你 snapshot 用的哪个组件？

snapshot-phantomjs 0.0.3
https://github.com/pyecharts/snapshot-phantomjs

本地的phantomjs版本是2.1.1

**Comment by sunhailin-Leo** [comment]
> > @exqmjmz
> > 
> > * 你 snapshot 用的哪个组件？
> 
> snapshot-phantomjs 0.0.3 https://github.com/pyecharts/snapshot-phantomjs
> 
> 本地的phantomjs版本是2.1.1

试试我说的那两个吧。。phantomjs 都 public archive 了。。社区不更新了

**Comment by exqmjmz** [comment]
> > > @exqmjmz
> > > 
> > > * 你 snapshot 用的哪个组件？
> > 
> > 
> > snapshot-phantomjs 0.0.3 https://github.com/pyecharts/snapshot-phantomjs
> > 本地的phantomjs版本是2.1.1
> 
> 试试我说的那两个吧。。phantomjs 都 public archive 了。。社区不更新了

pyppeteer 也是像phantomjs的情况，html渲染正常，输出雷达图报错，但是像地图、饼图都能正常输出

pyppeteer用pyecharts的make_snapshot去获取图片是直接报错的
```
2024-11-14 18:48:33,236 - ERROR - 服务器内部错误: Navigation Timeout Exceeded: 30000 ms exceeded.
Traceback (most recent call last):
  File "/Users/************/code/************/src/main.py", line 49, in radar
    radar.render()
  File "/Users/************/code/************/src/radar.py", line 82, in render
    self._renderRadar()
  File "/Users/************/code/************/src/radar.py", line 101, in _renderRadar
    make_snapshot(snapshot, self.htmlPath, self.imagePath)
  File "/Users/************/code/************/venv/lib/python3.9/site-packages/pyecharts/render/snapshot.py", line 32, in make_snapshot
    content = engine.make_snapshot(
  File "/Users/************/code/************/venv/lib/python3.9/site-packages/snapshot_pyppeteer/snapshot.py", line 73, in make_snapshot
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/************/code/************/venv/lib/python3.9/site-packages/snapshot_pyppeteer/snapshot.py", line 44, in run_snapshot
    await page.setJavaScriptEnabled(enabled=True)
  File "/Users/************/code/************/venv/lib/python3.9/site-packages/pyppeteer/page.py", line 838, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
127.0.0.1 - - [14/Nov/2024 18:48:33] "POST /chart/radar HTTP/1.1" 500 70
```
如果通过pyppeteer的示例代码去调试是正常的，以下是pyppeteer的示例代码
```
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto("file:///Users/*********/code/*********/src/static/image/radar1731580996427568.html")
    await page.screenshot({'path': '111.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by exqmjmz** [comment]
以下是生成出来的html文件,echarts.min.js,版本5.5.1
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
                <script type="text/javascript" src="http://localhost:8888/static/js/echarts.min.js"></script>

</head>
<body >
    <div id="f13e87acc9f24c4da1640595370be609" class="chart-container" style="width:1000px; height:1000px; "></div>
    <script>
        var chart_f13e87acc9f24c4da1640595370be609 = echarts.init(
            document.getElementById('f13e87acc9f24c4da1640595370be609'), 'white', {renderer: 'canvas'});
        var option_f13e87acc9f24c4da1640595370be609 = {
    "backgroundColor": "white",
    "animation": true,
    "animationThreshold": 2000,
    "animationDuration": 1000,
    "animationEasing": "cubicOut",
    "animationDelay": 0,
    "animationDurationUpdate": 300,
    "animationEasingUpdate": "cubicOut",
    "animationDelayUpdate": 0,
    "aria": {
        "enabled": false
    },
    "color": [
        "#5470c6",
        "#91cc75",
        "#fac858",
        "#ee6666",
        "#73c0de",
        "#3ba272",
        "#fc8452",
        "#9a60b4",
        "#ea7ccc"
    ],
    "series": [
        {
            "type": "radar",
            "data": [
                {
                    "name": "Allocated Budget",
                    "value": [
                        4200,
                        3000,
                        20000,
                        35000,
                        50000,
                        18000
                    ],
                    "symbolKeepAspect": false
                },
                {
                    "name": "Actual Spending",
                    "value": [
                        5000,
                        14000,
                        28000,
                        26000,
                        42000,
                        21000
                    ],
                    "symbolKeepAspect": false
                }
            ],
            "label": {
                "show": true,
                "margin": 8,
                "valueAnimation": false
            },
            "selectedMode": false,
            "zlevel": 0,
            "z": 2,
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "show": true,
                "width": 1,
                "opacity": 1,
                "curveness": 0,
                "type": "solid"
            },
            "areaStyle": {
                "opacity": 0
            }
        }
    ],
    "legend": [
        {
            "data": [
                "Allocated Budget",
                "Actual Spending"
            ],
            "selected": {}
        }
    ],
    "tooltip": {
        "show": true,
        "trigger": "item",
        "triggerOn": "mousemove|click",
        "axisPointer": {
            "type": "line"
        },
        "showContent": true,
        "alwaysShowContent": false,
        "showDelay": 0,
        "hideDelay": 100,
        "enterable": false,
        "confine": false,
        "appendToBody": false,
        "transitionDuration": 0.4,
        "textStyle": {
            "fontSize": 14
        },
        "borderWidth": 0,
        "padding": 5,
        "order": "seriesAsc"
    },
    "radar": [
        {
            "indicator": [
                {
                    "name": "Sales",
                    "max": 5500.0
                },
                {
                    "name": "Administration",
                    "max": 15400.0
                },
                {
                    "name": "Information Technology",
                    "max": 30800.0
                },
                {
                    "name": "Customer Support",
                    "max": 38500.0
                },
                {
                    "name": "Development",
                    "max": 55000.0
                },
                {
                    "name": "Marketing",
                    "max": 23100.0
                }
            ],
            "startAngle": 90,
            "name": {
                "textStyle": {}
            },
            "splitLine": {
                "show": true,
                "lineStyle": {
                    "show": true,
                    "width": 1,
                    "opacity": 1,
                    "curveness": 0,
                    "type": "solid"
                }
            },
            "splitArea": {
                "show": true,
                "areaStyle": {
                    "opacity": 0
                }
            },
            "axisLine": {
                "show": true,
                "onZero": true,
                "onZeroAxisIndex": 0
            }
        }
    ]
};
        chart_f13e87acc9f24c4da1640595370be609.setOption(option_f13e87acc9f24c4da1640595370be609);
    </script>
</body>
</html>

```

**Comment by sunhailin-Leo** [comment]
@exqmjmz 
* 抱歉这么久才回复～
* 你这个空白应该和你 `http://localhost:8888/static/js/echarts.min.js` 有关系吧？你加了一层代理。
* 我这边本地测试的 pyppeteer 没有渲染的问题
