### ISSUE TITLE
pyecharts + django

### ISSUE THREAD

**Issue by yangzinan** [pyecharts/pyecharts#541]
我在Django 里面只要import pyecharts，django就无法启动报错如下（Django1.11.4，pyecharts==0.52）
```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000000058F1620>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\utils\six.py", line 191, in __get_module
    return self.known_modules[fullname]
KeyError: 'django.contrib.messages.migrations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\core\management\commands\runserver.py", line 128, in inner_run
    self.check_migrations()
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\core\management\base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\db\migrations\executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\db\migrations\loader.py", line 52, in __init__
    self.build_graph()
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\db\migrations\loader.py", line 203, in build_graph
    self.load_disk()
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\db\migrations\loader.py", line 82, in load_disk
    module = import_module(module_name)
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\macropy\core\import_hooks.py", line 134, in find_spec
    source = spec.loader.get_source(fullname)
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\utils\six.py", line 222, in get_code
    self.__get_module(fullname)  # eventually raises ImportError
  File "C:\ProgramData\Miniconda3\envs\myapp\lib\site-packages\django\utils\six.py", line 193, in __get_module
    raise ImportError("This loader does not know module " + fullname)
ImportError: This loader does not know module django.contrib.messages.migrations
```

**Comment by kinegratii** [comment]
please show your demo code.

**Comment by kinegratii** [comment]
Related issue: https://github.com/kinegratii/django-echarts/issues/17

**Comment by kinegratii** [comment]
This bug is brought on pyecharts v0.5.0+.

Temporarily solution: Roll back to v0.4.1

**Comment by yangzinan** [comment]
谢啦降级就好使了

**Comment by chfw** [comment]
pip install javascripthon==0.1.0 works


Will make a proper fix later

**Comment by chfw** [comment]
装pyecharts-javascripthon version 0.0.6 也是同样的。
