### ISSUE TITLE
保存图片失败 - 求帮忙

### ISSUE THREAD

**Issue by lzy305** [pyecharts/pyecharts#556]
pyecharts: 0.5.3，
 Python : 3.5.2

需求: 生成图片
from pyecharts import configure
from pyecharts import Bar
configure(output_image='png')
bar = Bar("我的第一个图表", "这里是副标题")
bar.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])
bar.render(path='a.png')

错误信息： 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/base.py", line 126, in render
    env = engine.create_default_environment(_file_type)
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/engine.py", line 269, in create_default_environment
    [config.echarts_template_dir, default_template_dir]
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/engine.py", line 249, in get_a_environment
    key=file_type
  File "/usr/local/lib/python3.5/dist-packages/lml/plugin.py", line 289, in load_me_now
    self.raise_exception(key)
  File "/usr/local/lib/python3.5/dist-packages/lml/plugin.py", line 240, in raise_exception
    "No %s is found for %s" % (self.plugin_name, key))
Exception: No pyecharts_environment is found for png

**Comment by chenjiandongx** [comment]
http://pyecharts.org/#/zh-cn/prepare

![image](https://user-images.githubusercontent.com/19553554/40044619-7e10dbda-585a-11e8-87ad-c36f4cbdbd5e.png)

**Comment by 97612336** [comment]
> http://pyecharts.org/#/zh-cn/prepare
> 
> ![image](https://user-images.githubusercontent.com/19553554/40044619-7e10dbda-585a-11e8-87ad-c36f4cbdbd5e.png)

这个并不起作用，我试了下，并不行

**Comment by zonenAnna** [comment]
pyechart-snapshot版本太老了
