### ISSUE TITLE
AttributeError: module 'pyecharts' has no attribute 'utils'

### ISSUE THREAD

**Issue by ahbon123** [pyecharts/pyecharts#625]
求助，导入模块时from pyecharts import Bar产生如下报错：

Traceback (most recent call last):

  File "<ipython-input-114-e2aefc3a250b>", line 1, in <module>
    from pyecharts import Bar

  File "C:\Users\User\Anaconda3\lib\site-packages\pyecharts\__init__.py", line 38, in <module>
    from pyecharts.custom.page import Page

  File "C:\Users\User\Anaconda3\lib\site-packages\pyecharts\custom\page.py", line 7, in <module>
    import pyecharts.utils as utils

AttributeError: module 'pyecharts' has no attribute 'utils'

**Comment by chfw** [comment]
please make sure you have pyecharts installed in your current python environment. Typically, you have install pyecharts in a global environment, then you try to import it in your virtual python environment, you will get this exception.

**Comment by chenjiandongx** [comment]
@ahbon123 不要把你的文件命名为 pyecharts.py
