### ISSUE TITLE
set pyecharts_snapshot in requirements

### ISSUE THREAD

**Issue by LionelR** [pyecharts/pyecharts#815]
pyecharts can't be imported if pyecharts_snapshot is not installed:
```
ERROR:lml.utils:failed to import pyecharts_snapshot
Traceback (most recent call last):
  File "/tmp/test_flask_logging/venv/lib/python3.6/site-packages/lml/utils.py", line 43, in do_import
    plugin_module = __import__(plugin_module_name)
ModuleNotFoundError: No module named 'pyecharts_snapshot'
```

**Comment by linhuaiyi** [comment]
pip install pyecharts-snapshot

**Comment by LionelR** [comment]
We know that, but as a necessary package dependency to run it should be listed in the requirements

**Comment by chfw** [comment]
Nope it is an optional package and the unit tests are done without it and are passing.

**Comment by LionelR** [comment]
And so you have a problem in your tests
```bash
 test_pyecharts $ virtualenv venv
Using base prefix '/usr'
New python executable in /tmp/test_pyecharts/venv/bin/python3
Also creating executable in /tmp/test_pyecharts/venv/bin/python
Installing setuptools, pip, wheel...done.
 test_pyecharts $ source venv/bin/activate.fish 
(venv)  test_pyecharts $ pip install pyecharts
Collecting pyecharts
  Using cached https://files.pythonhosted.org/packages/52/b8/e46a41c44176cd247cb1fd437e38e179ea604de28c91755c30be1046772c/pyecharts-0.5.11-py2.py3-none-any.whl
Collecting pillow (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/62/94/5430ebaa83f91cc7a9f687ff5238e26164a779cca2ef9903232268b0a318/Pillow-5.3.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting lml==0.0.2 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/8a/6f/0eb22694df07072ea467effdbb8e313222a21788ea7914773f59fd2bb857/lml-0.0.2-py2.py3-none-any.whl
Collecting future (from pyecharts)
  Downloading https://files.pythonhosted.org/packages/85/aa/ba2e24dcb889d7e98733f87515d80b3512418b80ba79d82d2ddcd43fadf3/future-0.17.0.tar.gz (827kB)
    100% |████████████████████████████████| 829kB 4.9MB/s 
Collecting pyecharts-javascripthon==0.0.6 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/6f/68/23644a394341fef4cbcb48a3fa4b2816408a13a1fa3281cf9030b2ac2d67/pyecharts_javascripthon-0.0.6-py2.py3-none-any.whl
Collecting jinja2 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting jupyter-echarts-pypkg==0.1.2 (from pyecharts)
Collecting javascripthon>=0.10; python_version > "3.4" (from pyecharts-javascripthon==0.0.6->pyecharts)
Collecting MarkupSafe>=0.23 (from jinja2->pyecharts)
Collecting pyecharts-jupyter-installer==0.0.3 (from jupyter-echarts-pypkg==0.1.2->pyecharts)
  Using cached https://files.pythonhosted.org/packages/9e/cd/4b0b594857f7ca078f2a3f75e02d4c8db666d47ce9433d2ce9e241e5eb55/pyecharts_jupyter_installer-0.0.3-py2.py3-none-any.whl
Collecting macropy3==1.1.0b2 (from javascripthon>=0.10; python_version > "3.4"->pyecharts-javascripthon==0.0.6->pyecharts)
Collecting dukpy (from javascripthon>=0.10; python_version > "3.4"->pyecharts-javascripthon==0.0.6->pyecharts)
  Using cached https://files.pythonhosted.org/packages/32/01/9690b743bb058559b91e1e290bad4bda68d7bc572bc1c06c77c664161436/dukpy-0.2.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from javascripthon>=0.10; python_version > "3.4"->pyecharts-javascripthon==0.0.6->pyecharts) (40.4.3)
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/lionel/.cache/pip/wheels/fc/5b/ec/2983c4a6e3692d1315f44d6480c6abdd8585d96471b431d6b4
Successfully built future
Installing collected packages: pillow, lml, future, macropy3, dukpy, javascripthon, pyecharts-javascripthon, MarkupSafe, jinja2, pyecharts-jupyter-installer, jupyter-echarts-pypkg, pyecharts
Successfully installed MarkupSafe-1.0 dukpy-0.2.2 future-0.17.0 javascripthon-0.10 jinja2-2.10 jupyter-echarts-pypkg-0.1.2 lml-0.0.2 macropy3-1.1.0b2 pillow-5.3.0 pyecharts-0.5.11 pyecharts-javascripthon-0.0.6 pyecharts-jupyter-installer-0.0.3
(venv)  test_pyecharts $ python
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyecharts
ERROR:lml.utils:failed to import pyecharts_snapshot
Traceback (most recent call last):
  File "/tmp/test_pyecharts/venv/lib/python3.6/site-packages/lml/utils.py", line 43, in do_import
    plugin_module = __import__(plugin_module_name)
ModuleNotFoundError: No module named 'pyecharts_snapshot'
>>> 
```

**Comment by chfw** [comment]
Please track the issue there.

**Comment by chfw** [comment]
@LionelR, if you try the following for your virtual enviroment:`virtualenv --no-site-packages venv`, would you still get it?

**Comment by chfw** [comment]
I suspect in your global environment, you have pyecharts_snapshot installed.

**Comment by LionelR** [comment]
If I have the pyecharts_snapshot installed in the global env, the error will not raised. Trying with --no-site-packages changes nothing, the problem is in the js_extensions.py file and more closely at line 13
```
OFFICIAL_PLUGINS = ["jupyter_echarts_pypkg", "pyecharts_snapshot"]
```
Removing the "pyecharts_snapshot" entry and the initial import goes fine.

**Comment by chfw** [comment]
OK. I got it now: https://github.com/chfw/lml/blob/master/lml/loader.py#L123
