### ISSUE TITLE
windows python脚本移植到CentOS，内容不变会报错

### ISSUE THREAD

**Issue by lsaiah** [pyecharts/pyecharts#922]
**问题**
windows python脚本移植到CentOS，内容不变会报错

**运行环境（系统环境及 pyecharts 版本）**
windows为0.5.11，pycharts-snapshot为0.1.10，linux为相同版本
windows为Python3.6.0,linux为3.6.3
windows为win7 旗舰版，linux为CentOS Linux release 7.6.1810

**代码及截图**

报错为
Traceback (most recent call last):
  File "report.py", line 93, in <module>
    freespace.render(path='/root/freespace.png',pixel_ratio=1)
  File "/usr/local/lib/python3.6/site-packages/pyecharts/base.py", line 146, in render
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pyecharts_snapshot/environment.py", line 39, in render_chart_to_file
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pyecharts/engine.py", line 220, in render_chart_to_file
    html = tpl.render(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/pyecharts/templates/simple_chart.html", line 10, in top-level template code
    {{ echarts_js_content(chart) }}
  File "/usr/local/lib/python3.6/site-packages/pyecharts/engine.py", line 129, in echarts_js_content
    return Markup(EMBED_SCRIPT_FORMATTER.format(generate_js_content(*charts)))
  File "/usr/local/lib/python3.6/site-packages/pyecharts/engine.py", line 101, in generate_js_content
    javascript_snippet = TRANSLATOR.translate(chart.options)
  File "/usr/local/lib/python3.6/site-packages/pyecharts_javascripthon/api.py", line 127, in translate
    option_snippet = json.dumps(options, indent=4, cls=self.json_encoder)
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.6/site-packages/pyecharts_javascripthon/api.py", line 118, in default
    return super(DefaultJsonEncoder, self).default(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Decimal' is not JSON serializable

代码此段为

line = pyecharts.Line("历史表空间使用量",width=800,height=400)
#get date and time
tablespace = cursor.fetchmany(30)
#图表数值自动生成
timestamp=[]
tbusesize=[]
for rows in tablespace:
    timestamp.append(rows[0])
    tbusesize.append(rows[1])
#图表自动生成
line.add("使用量(GB)",timestamp,tbusesize,yaxis_min='3000')
#图片生成
line.render(path='line.png',pixel_ratio=1)
page.add(line)

windows环境代码是无报错的，到linux环境装了linux版的pycharm也会报相同的错觉，怀疑是环境不一致却没有什么太好的思路

**Comment by chfw** [comment]
你的数据里含有'Decimal'

**Comment by lsaiah** [comment]
好的，多谢您的回答，我尝试改变传入的数据试一试

**Comment by lsaiah** [comment]
另外，想请问一下，为什么windows不会有问题？

**Comment by chfw** [comment]
请问这个库： tablespace = cursor.fetchmany(30)

**Comment by lsaiah** [comment]
传入的是DB表空间的量，数据是如下一样的
1	01/22/2019	4767	78.61
2	01/23/2019	4824	79.54
3	01/24/2019	4844	79.88
4	01/25/2019	4868	80.27
省略……

**Comment by chfw** [comment]
是哪个库？它的版本在windows 和centos 一样吗？

**Comment by chfw** [comment]
你有用requirements.txt严控版本么？

**Comment by lsaiah** [comment]
是的，是一套Oracle库，连接的是同一套DB

**Comment by lsaiah** [comment]
恩，因为隔离，所以并没有使用requirements.txt同步版本

**Comment by lsaiah** [comment]
我将传入的参数的位数减少就不会报错了，谢谢
